<a href="https://colab.research.google.com/github/armandoh2/ejercicioclaseangelh/blob/main/operaciones_matematicas_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
## ejercicio 3 operaciones matematicas
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])
print(a + b )

print(a / b)

print(a ** 2)





[[2 3 4]
 [6 7 8]]
[[1.  2.  3. ]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]
